export enum FormFieldType {
  'button',
  'checkbox',
  'color',
  'date',
  'datetime-local',
  'email',
  'file',
  'hidden',
  'image',
  'month',
  'number',
  'password' = 'password',
  'radio' = 'radio',
  'range' = 'range',
  'reset' = 'reset',
  'search' = 'search',
  'submit' = 'submit',
  'tel' = 'tel',
  'text' = 'text',
  'time' = 'time',
  'url' = 'url',
  'week' = 'week',
}
